approve_by_comment: true
approve_regex: '^([Aa]pproved|:shipit:|:\+1:|I [Aa]pprove)'
reject_regex: ^Rejected
reset_on_push: false
author_approval: ignored
reviewers:
  members:
  - ajkunen
  - keasler
  - rhornung67
  - trws
  name: pullapprove
  required: 2
