coverage:
  precision: 3
  round: down
  range: "80...100"

  status:
    project: yes
    patch: yes
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: no
      loop: no
      method: yes
      macro: yes

ignore:
  - "**/test-*.cpp"

comment:
  layout: "header, diff, files, tree"
  behavior: default
  require_changes: no
